version: "3.9"

services:
    postgresContainer:
        container_name: "postgres_php"
        image: postgres
        hostname: localhost
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=laravel
            - TZ=America/Sao_Paulo
        volumes:
            - postgres_docker:/var/lib/postgresql/dat

volumes:
    postgres_docker:
